accounts/urls.py
from django.urls import re_path as url 

from . import views


app_name = 'accounts' 

urlpatterns = [

	url(r'^login/$', views.login, name="login"),
	url(r'^logout/$', views.logout, name="logout"),
	url(r'^signup/$', views.signup, name="signup"),
]

posts/urls.py
from django.urls import re_path as url 

from . import views

app_name = 'posts' 


urlpatterns = [

		url(r'^$', views.dashboard, name="dashboard"),
		url(r'^create-post/$', views.create_post, name="create_post"),
		url(r'^block-user/$', views.block_user, name="block_user"),
		
		url(r'^blocked-user-alert/$', views.blocked_user_alert, name="blocked_user_alert"),
]

social_app/urls.py
from django.conf.urls import  include
from django.urls import re_path as url 
from django.contrib import admin
from django.conf.urls.static import static 
from django.conf import settings



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include("accounts.urls", namespace="accounts")),
    url(r'^', include("posts.urls", namespace="posts")),
]
if settings.DEBUG:

	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Post(models.Model):
	id = models.AutoField(primary_key=True)
	title = models.CharField(max_length=255)
	post = models.TextField()
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	created_at = models.DateTimeField(auto_now=True)
	blocked = models.BooleanField(default=False)

	class Meta:
		db_table = "posts"
		ordering = ["-id"]

	def __str__(self):

		return self.title


class BlockedPost(models.Model):
	id = models.AutoField(primary_key=True)
	blocked_by = models.ForeignKey(User, on_delete=models.CASCADE,null=True, related_name='blocked_by')
	blocked_whom = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='blocked_whom')
	post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True)
	is_user_blocked = models.BooleanField(default=False)

	class Meta:
		db_table = "blocked_post"
		ordering = ["-id"]

	def __str__(self):
		return str(self.pk)

accounts/forms.py
from django import forms 
from django.contrib.auth import authenticate
from django.contrib.auth.models import User


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            user = authenticate(username=username, password=password)
            # import pdb; pdb.set_trace()
            if not user:
                # raise forms.ValidationError('This user does not exists')
                self.add_error("username", 'Invalid Username or Password')
            if user:
                if not user.is_active:
                    # raise forms.ValidationError('This user is no longer active.')
                    self.add_error("username", 'Invalid Username or Password')
        return self.cleaned_data



class SignUpForm(forms.Form):

    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.EmailField()
    password1 = forms.CharField()
    password2 = forms.CharField()


    def clean_email(self):
        email = self.cleaned_data.get("email")
        if email:
            qs = User.objects.filter(email__iexact=email)
            if qs.exists():
                self.add_error("email", "This Email Id already existed.")
        return email

    def clean(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")

        if password1 != password2:
            self.add_error("password1", "Please enter the same password")

        self.cleaned_data

posts/forms.py
import re

from django import forms 

from .models import Post, BlockedPost

from generic.models import BadWordList
from generic.utils import check_content

from django.contrib.auth import logout

import nltk
sno = nltk.stem.SnowballStemmer('english')
lemma = nltk.wordnet.WordNetLemmatizer()
from flashtext import KeywordProcessor
from nltk.tokenize import RegexpTokenizer

tokenizer = RegexpTokenizer(r'\w+')
# import hunspell
# hobj = hunspell.HunSpell('/usr/share/myspell/en_US.dic', '/usr/share/myspell/en_US.aff')

# hobj.stem('linked')
# lemma.lemmatize('leaves')


class PostForm(forms.ModelForm):

	def __init__(self, *args, **kwargs):
		self.request = kwargs.pop("request")
		super(PostForm, self).__init__(*args, **kwargs)


	class Meta:
		model = Post
		fields = ("title", "post")

	def clean_title(self):
		title = self.cleaned_data.get("title", "")
		the_title = title
		# keyword_processor = KeywordProcessor()
		# if title:
		# 	blocked_words = BadWordList.objects.filter(
		# 								active=True
		# 						)
		# 	blocked_words_count = blocked_words.count()

		# 	bad_word_list = []
		# 	stemmed_words = []
		# 	for word in blocked_words:
		# 		if not word.word in bad_word_list:
		# 			bad_word_list.append(word.word)
		# 	tokenized_words = tokenizer.tokenize(title)

		# 	for word in tokenized_words:
		# 		word = word.lower()
		# 		if word not in stemmed_words:
		# 			word = sno.stem(word)
		# 			stemmed_words.append(word)
		# 	count=0
		# 	while count < len(tokenized_words):
		# 		word = tokenized_words[count]
		# 		word = word.lower()
		# 		word = lemma.lemmatize(word)
		# 		count += 1

		# 		if word not in stemmed_words:
		# 			stemmed_words.append(word)

			
		# 	tokenized_list = list(set(tokenized_words))

		# 	word_list = tokenized_list + stemmed_words
		# 	word_list = list(set(word_list))

		# 	title = " ".join(word_list)


		# 	for word in bad_word_list:
		# 		keyword_processor.add_keyword(word)

		# 	keywords_found = keyword_processor.extract_keywords(title)

		# 	found = False
		# 	found_list = ""
		# 	re_found_list = []

		# 	for item in bad_word_list:
		# 		if re.search(
		# 				item, 
		# 				title, 
		# 				re.IGNORECASE
		# 			):

		# 			found_word = item.lower() 
		# 			re_found_list.append(found_word)
		# 			found = True
		# 			found_list += "%s " %(item)

		# 	if found or len(keywords_found) > 0:
		# 		bad_word_found_list = []
		# 		word_found_list = re_found_list + keywords_found
		# 		for word in word_found_list:
		# 			if not word in bad_word_found_list:
		# 				bad_word_found_list.append(word)

		# 		bad_word_found_count = len(bad_word_found_list)

		# 		bad_word_percentage = (bad_word_found_count * 100)/blocked_words_count

		result = check_content(the_title)
		print (result, "result from the api")
		if result in ['bad']:
		# 	if not  BlockedPost.objects.filter(
		# 					blocked_by__isnull=True,
		# 					blocked_whom=self.request.user
		# 				).exists():
		# 		blocked_obj = BlockedPost.objects.create(
		# 					blocked_whom=self.request.user
		# 				)
		# 	self.add_error(
		# 		"title", 
		# 		"Too many bad words. Your account has been blocked. Contact administrator"
		# 	)
			
		# 	return the_title
		# found_list = ",".join(bad_word_found_list)
			self.add_error(
					"title", 
					"Please review the content"
					# "Blocked words (%s) found in your title" %(found_list)
						)
		return the_title

	def clean_post(self):
		title = self.cleaned_data.get("post", "")
		the_title = title
		# keyword_processor = KeywordProcessor()
		# if title:
		# 	blocked_words = BadWordList.objects.filter(
		# 								active=True
		# 						)
		# 	blocked_words_count = blocked_words.count()

		# 	bad_word_list = []
		# 	stemmed_words = []
		# 	for word in blocked_words:
		# 		if not word.word in bad_word_list:
		# 			bad_word_list.append(word.word)
		# 	tokenized_words = tokenizer.tokenize(title)

		# 	for word in tokenized_words:
		# 		word = word.lower()
		# 		if word not in stemmed_words:
		# 			word = sno.stem(word)
		# 			stemmed_words.append(word)
		# 	count=0
		# 	while count < len(tokenized_words):
		# 		word = tokenized_words[count]
		# 		word = word.lower()
		# 		word = lemma.lemmatize(word)
		# 		count += 1

		# 		if word not in stemmed_words:
		# 			stemmed_words.append(word)

			
		# 	tokenized_list = list(set(tokenized_words))

		# 	word_list = tokenized_list + stemmed_words
		# 	word_list = list(set(word_list))

		# 	title = " ".join(word_list)


		# 	for word in bad_word_list:
		# 		keyword_processor.add_keyword(word)

		# 	keywords_found = keyword_processor.extract_keywords(title)

		# 	found = False
		# 	found_list = ""
		# 	re_found_list = []

		# 	for item in bad_word_list:
		# 		if re.search(
		# 				item, 
		# 				title, 
		# 				re.IGNORECASE
		# 			):

		# 			found_word = item.lower() 
		# 			re_found_list.append(found_word)
		# 			found = True
		# 			found_list += "%s " %(item)

		# 	if found or len(keywords_found) > 0:
		# 		bad_word_found_list = []
		# 		word_found_list = re_found_list + keywords_found
		# 		for word in word_found_list:
		# 			if not word in bad_word_found_list:
		# 				bad_word_found_list.append(word)

		# 		bad_word_found_count = len(bad_word_found_list)

		# 		bad_word_percentage = (bad_word_found_count * 100)/blocked_words_count


		result = check_content(the_title)
		print (result, "result from the api")
		if result in ['bad']:
			# if not  BlockedPost.objects.filter(
			# 				blocked_by__isnull=True,
			# 				blocked_whom=self.request.user
			# 			).exists():
			# 	blocked_obj = BlockedPost.objects.create(
			# 				blocked_whom=self.request.user
			# 			)
			# self.add_error(
			# 	"post", 
			# 	"Too many bad words. Your account has been blocked. Contact administrator"
			# )
			
		# 	return the_title
		# found_list = ",".join(bad_word_found_list)
			self.add_error(
					"post",
					"Please review the content" 
					# "Blocked words (%s) found in your title" %(found_list)
						)
		return the_title


class BlockForm(forms.Form):

	post_id = forms.IntegerField()
	words = forms.CharField(required=False)
	is_user_blocked = forms.BooleanField(initial=False, required=False)
	is_post_blocked = forms.BooleanField(initial=False, required=False)

templates/auth_base.html
<!doctype html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8" />
    <title>MYBook Login or Sign Up</title>
    <link rel="shortcut icon" type="image/x-icon" href="" />
    <link rel="stylesheet" href="{% static 'css/auth_style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/toastr.min.css' %}" />

</head>

<body>

    <div class="loading" style="">
       <div class="sk-circle">
  <div class="sk-circle1 sk-child"></div>
  <div class="sk-circle2 sk-child"></div>
  <div class="sk-circle3 sk-child"></div>
  <div class="sk-circle4 sk-child"></div>
  <div class="sk-circle5 sk-child"></div>
  <div class="sk-circle6 sk-child"></div>
  <div class="sk-circle7 sk-child"></div>
  <div class="sk-circle8 sk-child"></div>
  <div class="sk-circle9 sk-child"></div>
  <div class="sk-circle10 sk-child"></div>
  <div class="sk-circle11 sk-child"></div>
  <div class="sk-circle12 sk-child"></div>
</div>
    </div>

    <header>
        <section class="wrapper">
            <div class="logo">
                <h1>
                    <a href="#">MYBook</a>
                </h1>
            </div>
            <div class="loginform">
                <form action="" id="login">
                {% csrf_token %}
                    <table>
                        <tr class="label">
                            <td><label for="username"> Email or Phone </label></td>
                            <td><label for="password">Password</label></td>
                        </tr>
                        <tr class="input">
                            <td><input type="text" name="username" id="id_username" /></td>
                            <td><input type="password" name="password" id="id_password" /></td>
                            <td class="submit"><input type="submit" value="Log In" /></td>
                        </tr>
                        <tr class="link">
                            <td>
                                <input type="checkbox" name="keepmeloggedin" id="keepmeloggedin" />
                                <label class="remember" for="keepmeloggedin">Keep me logged in</label>
                            </td>
                            <td>
                                <a class="forgot_pw" href="">Forgotten your password?</a>
                            </td>
                        </tr>
                    </table>
                    <br class="clear" />
                </form>
            </div>
            <br class="clear" />
        </section>
    </header>
    <section id="content">
        <section class="wrapper">
            <section class="contentleft">
                <h4>MYBook help you connect and share with the people in your life</h4>
                <img src="{% static 'images/facebook.png' %}" alt="facebook connecting people" />
            </section>
            <section class="contentright">
                <h2>Create an account</h2>
                <h5>Register for free.</h5>
                <form action="" id="signup">
                {% csrf_token %}
                <div id="signupform">
                    <div id="fullname" class="inp">
                        <input type="text" name="first_name" placeholder="First name" id="id_first_name" required/>
                        <input type="text" name="last_name" placeholder="Surname" id="id_last_name" required/>
                    </div>
                    <div id="emailormobile" class="sameinp inp">
                        <input type="email" id="id_email" name="email" placeholder="Email" required/>
                    </div>
                    <div id="renteremailormobile" class="sameinp inp">
                        <input type="password" id="id_password1" name="password1" placeholder="password" required/>
                    </div>
                    <div id="password" class="sameinp inp">
                        <input type="password" name="password2" placeholder="Re-enter password" id="id_password2" required/>
                    </div>
                    <div id="password" class="sameinp">
                        <input type="submit" class="submit" value="Create Account">
                    </div>
                </div>
                </form>
            </section>
            <br class="clear" />
        </section>
    </section>


<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
<script src="{% static 'js/toastr.min.js' %}"></script>
<script>
    
    $(document).ready(function(){

        
        $("#signup").submit(function(e){
            e.preventDefault();
            $this = $(this);
            var data = $this.serialize();
            var url = "{% url 'accounts:signup' %}"
            var method = "post"
            show("loading");
            $.ajax({
                url:url,
                dataType:"JSON",
                type:method,
                data:data,
                success:function(data){
                     hide("loading");
                    var status = data["status"]
                    var message = data["message"]

                    if (status >0){
                        var redirect = data["redirect"]
                        toastr.success(message);
                        window.location.href = redirect;
                        
                    }
                    else{
                        toastr.warning("Please correct the errors.");
                          var errors = data["errors"]
                        var errors = data["errors"]
                        $.each(errors, function(key, value){
                            
                            console.log(key+":"+value)
                            var input_id = "#id_"+key;
                            $input_parent = $this.find("#id_"+key).parent("div");
                            $input_parent.find("label.error").remove();

                             var label_error = '<label class="error" for="'+input_id+'">'+value+'.</label>'

                             $input_parent.append(label_error);
                        });

                    }
                },
                error:function(data){
                     hide("loading");
                     toastr.warning("Server errors occured");
                }
            }); 
            
        });


    

        $("#login").submit(function(e){
            e.preventDefault();
            $this = $(this);
            var data = $this.serialize();
            var url = "{% url 'accounts:login' %}"
            var method = "post"
            show("loading");
            $.ajax({
                url:url,
                dataType:"JSON",
                type:method,
                data:data,
                success:function(data){
                     hide("loading");
                    var status = data["status"]
                    var message = data["message"]

                    if (status >0){
                        var redirect = data["redirect"]
                        toastr.success(message);
                        window.location.href = redirect;
                        
                    }
                    else{
                        toastr.warning("Please correct the errors.");
                          var errors = data["errors"]
                        var errors = data["errors"]
                        $.each(errors, function(key, value){
                            
                            console.log(key+":"+value)
                            var input_id = "#id_"+key;
                            $input_parent = $this.find("#id_"+key).parent("td");
                            $input_parent.find("label.error").remove();

                             var label_error = '<label class="error" for="'+input_id+'">'+value+'.</label>'

                             $input_parent.append(label_error);
                        });

                    }
                },
                error:function(data){
                     hide("loading");
                     toastr.warning("Server errors occured");
                }
            }); 
            
        });

        

    });
</script>

</body>

</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
  <meta charset="UTF-8">
  <title>MYBook</title>
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/toastr.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
  
</head>
<body>

    <div class="loading" style="">
       <div class="sk-circle">
  <div class="sk-circle1 sk-child"></div>
  <div class="sk-circle2 sk-child"></div>
  <div class="sk-circle3 sk-child"></div>
  <div class="sk-circle4 sk-child"></div>
  <div class="sk-circle5 sk-child"></div>
  <div class="sk-circle6 sk-child"></div>
  <div class="sk-circle7 sk-child"></div>
  <div class="sk-circle8 sk-child"></div>
  <div class="sk-circle9 sk-child"></div>
  <div class="sk-circle10 sk-child"></div>
  <div class="sk-circle11 sk-child"></div>
  <div class="sk-circle12 sk-child"></div>
</div>
    </div>
  <nav>
    <div class="nav_content">
      <div class="left left_nav">
        <div class="left">
            <div class="nav_img">
              <img src="{% static 'images/no-image.jpg' %}" alt="">
              <span class="username">{{ user.get_full_name }}</span>
            </div>
        </div>
        <div class="right menu_bars">
          <span class="fa fa-bars"></span>
        </div>
        <div class="clear"></div>
      </div>
      <div class="right right_nav">
        <ul class=>
          <li><a href="{% url 'posts:dashboard' %}"><span class="fa fa-home"></span> home</a></li>
          <li><a href="{% url 'posts:dashboard' %}"><span class="fa fa-refresh"></span> Refresh</a></li>
          <li><a href="#"><span class="fa fa-users"></span> friends</a></li>
          <li><a href="#"><span class="fa fa-cogs"></span> setting</a></li>
          <li><a href="{% url 'accounts:logout' %}"><span class="fa fa-sign-out"></span> logout</a></li>
        </ul>
        <div class="clear"></div>
      </div>
      <div class="clear"></div>
    </div>
  </nav>

  <div id="maincontent">
   
    <!-- left content starts here -->
    <div class="left_content left">
        
        <div class="left_top_content">
          <div class="friends_count">
            <span class="sub_title">
              Friends
            </span>
            <br>
            <span class="count">{{ user_count }}</span>
          </div>
          <div class="posts_count">
            <span class="sub_title">
              Posts
            </span>
            <br>
            <span class="count">{{ post_count }}</span>
          </div>
        </div>
        <div class="left_bottom_content">
        <h4>Friends List</h4>
            <ul class="friends_list">

              {% for user in users %}

              <li>
                <div>
                  <img src="{% static 'images/no-image.jpg' %}" alt="">
                  <span class="username">{{ user.get_full_name }}</span>
                </div>
              </li>
            
              {% endfor %}

            </ul>
            <div class="clear"></div>
        </div>
        <div class="clear"></div>

    </div>
    <!-- left content ends here -->

   <!-- left content starts here -->
    <div class="right_content left">
     
      <div class="page_heading">
        <span class="title">Posts</span>
      </div>
     

      <div class="new_post">
      <form action="" id="post_form">
      {% csrf_token %}
        <div id="post_form_container">

          <div style="margin-bottom:20px">
            <input type="text" name="title" placeholder="Enter your title here.." id="id_title">

          </div>
          <div>
            <textarea name="post" id="id_post" placeholder="Post your content here...."></textarea>
          </div>
          <div>
            <button class="post_btn pull-right" type="submit">Post <span class="fa fa-paper-plane-o"></span> </button>
            <div class="clearfix"></div>
          </div>
        </div>
        </form>
      </div>
      
      <!--- post title starts here -->
      {% for post in posts %}
      <div class="post_item">

        <div class="item_heading">
          <div style="display:inline-block">
            <img src="{% static 'images/no-image.jpg' %}" alt="">
          </div>
          <div class="item_title">
            <span class="posted">{% if not post.user == user %}{{ post.user.get_full_name }} {% else %} Me {% endif %} <i>posted this article</i></span>
            <br>
            <span class="post_date"><span class="fa fa-clock-o"></span> <i style="text-transform:capitalize">{{ post.created_at|date:'d b Y h:i A'}}</i></span>
          </div>
          {% if not post.user == user %}
            <div class="block_user pull-right" data-post="{{ post.pk }}">
                <span class="fa fa-ban text-danger block"></span>
            </div>
          {% endif %}
          <div class="clearfix"></div>
        </div>
        
        <div class="post_title">
          <h3>{{ post.title }}</h3>
          <p>
            {{ post.post }}
          </p>
        </div>

      </div>
      <!--- post title ends here -->
      {% endfor %}

    </div>
    <!-- right content ends here -->
    <div class="clear"></div>

  </div>
  <div class="post_layer"></div>
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/toastr.min.js' %}"></script>
  <script src="{% static 'js/script.js' %}"></script>
  
  <script>

  $(document).ready(function(){

    $("#id_title, #id_post").focus(function(){
      show("post_layer");
    }).focusout(function(){
      hide("post_layer");
    });


      $('#post_form').submit(function(e){
        e.preventDefault();

        $this = $(this);
        var data = $this.serialize();
        var url = "{% url 'posts:create_post' %}";
        var method = "post";
        $("label.error").remove();
       show("loading");
       $.ajax({
          url : url,
          type : method,
          dataType: "JSON",
          data : data,
          success:function(data){
            hide("loading");
            var status = data["status"]
            var message = data["message"]
            if (status >= 0){
                toastr.success(message);
                location.reload();
            }
            else{
              var refresh_page = data["refresh_page"]
              if (refresh_page < 0){
                location.reload();
              }

              var errors = data["errors"]
              toastr.warning("Please correct the errors.");
              var errors = data["errors"]
              var found_admin = false
               $.each(errors, function(key, value){
                    var str_val = String(value)
                    var n = str_val.indexOf("administrator");
                    console.log(n);
                    if (n>0){
                      found_admin = true
                    }      
                    console.log(key+":"+value)
                    var input_id = "#id_"+key;
                    $input_parent = $this.find("#id_"+key).parent("div");
                    $input_parent.find("label.error").remove();

                     var label_error = '<label class="error" for="'+input_id+'">'+value+'.</label>'

                     $input_parent.append(label_error);
                     $(input_id).focus();
                });

               if (found_admin){
                  setTimeout(function(){
                        location.reload();
                    },3000);
               }

            }
           
          },
          error:function(data){
            hide("loading");
            toastr.warning("Server errors occured");
          }
       });

      });



      $('#block_form').submit(function(e){
        e.preventDefault();

        $this = $(this);
        var data = $this.serialize();

        var url = "{% url 'posts:block_user' %}";
        var method = "post";
        $("label.error").remove();
       show("loading");
       $.ajax({
          url : url,
          type : method,
          dataType: "JSON",
          data : data,
          success:function(data){
            hide("loading");
            var status = data["status"]
            var message = data["message"]
            if (status >= 0){
                toastr.success(message);
                location.reload();
            }
            else{
              toastr.warning("Please correct the errors.");
              var errors = data["errors"]
               $.each(errors, function(key, value){
                            
                    console.log(key+":"+value)
                    var input_id = "#id_"+key;
                    $input_parent = $this.find("#id_"+key).parents(".parent_div");
                    $input_parent.find("label.error").remove();

                     var label_error = '<label class="error" for="'+input_id+'">'+value+'.</label>'

                     $input_parent.append(label_error);
                     
                });

            }
           
          },
          error:function(data){
            hide("loading");
            toastr.warning("Server errors occured");
          }
       });

      });


    $(".block").click(function(){
      var post_id = $(this).parent("div").data("post");
      $("#id_post_id").val(post_id);
      $('#myModal').modal('show')
    });
    
  

  });

  </script>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Block Content</h4>
      </div>
      <form action="" id="block_form">
      {% csrf_token %}
      <div class="modal-body">
          <input type="hidden" name="post_id" id="id_post_id" >
        <div id="post_form_container">

          <div style="margin-bottom:20px" class="parent_div">
            <input type="text" class="form-control" name="words" placeholder="Enter bad words with comma seperate" id="id_words">

          </div>
          <div class="parent_div">
            <label style="font-weight:100;"><input type="checkbox" name="is_post_blocked" id="id_is_post_blocked" style="margin-right:10px;">Block Post</label>
            <br>
          </div>
          <div class="parent_div">
            <label style="font-weight:100"><input style="margin-right:10px;"type="checkbox" id="id_is_user_blocked" name="is_user_blocked" >Block User</label>
            <br>
          </div>
          <div>
            
            <div class="clearfix"></div>
          </div>
        </div>
       
      </div>
      <div class="modal-footer">
        <button class="post_btn pull-right" type="submit">Block <span class="fa fa-ban"></span> </button>
      </div>
       </form>
    </div>

  </div>
</div>


</body>
</html>

templates/blocked_user_alert.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
  <meta charset="UTF-8">
  <title>MYBook</title>
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/toastr.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
  
</head>
<body>

<div class="alert alert-danger">
  <strong>Account Blocked!</strong> Please contact Administrator.
</div>

 <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/toastr.min.js' %}"></script>
  <script src="{% static 'js/script.js' %}"></script>
  

</body>
</html>